### PR TITLE
Add license files to packages

### LINKED ISSUE #24: Include LICENSE file in the installed node_modules
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Including the license file in the installed node_modules, makes the packages compatible with license checkers and attribution file generators, that a lot of developers need for generating copyrights/attribution files.

### Solution

Copy the license file into all packages.

### Alternatives

Nothing on my mind.

### PR DESCRIPTION
**Pull request by MarkAshraf96**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

Closes #24  
Added the license file to each package.
Added the license file to the included files in the package.json to be included in the package distribution.

### CODE REVIEW

**Comment by wooorm** [comment]
You don’t need to add `license` to `files` in `package.json`. They are always automatically included! Can you remove those changed? Thanks

**Comment by MarkAshraf96** [comment]
> You don’t need to add `license` to `files` in `package.json`. They are always automatically included! Can you remove those changed? Thanks

I didn't know that, thank you for the information. 
Modification done.

**Comment by wooorm** [comment]
I filled out the template for you. I am assuming you read and agreed to the docs ;)

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
[released](https://github.com/rehypejs/rehype-dom/releases/tag/7.0.1), thanks!

**Pull request merged**
